# Generated by Django 3.2 on 2021-09-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawl_tb',
            name='discraption',
        ),
        migrations.RemoveField(
            model_name='crawl_tb',
            name='urls',
        ),
        migrations.AddField(
            model_name='crawl_tb',
            name='identifier',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawl_tb',
            name='url',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crawl_tb',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
