# Generated by Django 3.2 on 2021-10-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0005_auto_20211019_0735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add',
        ),
    ]
