# Generated by Django 3.2 on 2021-10-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0006_delete_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawl_tb',
            old_name='identifier',
            new_name='discraption',
        ),
    ]
